import { ClassName } from "./ClassName";
import { DotaHero } from "src/types";


export const dotaHeroes: Array<DotaHero> = [
    { name: "Abaddon", imgName: "abaddon.png", className: ClassName.strength, pseudonym: "abaddon" },
    { name: "Alchemist", imgName: "alchemist.png", className: ClassName.strength, pseudonym: "alchemist" },
    { name: "Ancient Apparition", imgName: "ancient_apparition.png", className: ClassName.intelligence, pseudonym: "ancient_apparition" },
    { name: "Anti-Mage", imgName: "antimage.png", className: ClassName.agility, pseudonym: "antimage" },
    { name: "Arc Warden", imgName: "arc_warden.png", className: ClassName.agility, pseudonym: "arc_warden" },
    { name: "Axe", imgName: "axe.png", className: ClassName.strength, pseudonym: "axe" },
    { name: "Bane", imgName: "bane.png", className: ClassName.intelligence, pseudonym: "bane" },
    { name: "Batrider", imgName: "batrider.png", className: ClassName.intelligence, pseudonym: "batrider" },
    { name: "Beastmaster", imgName: "beastmaster.png", className: ClassName.strength, pseudonym: "beastmaster" },
    { name: "Bloodseeker", imgName: "bloodseeker.png", className: ClassName.agility, pseudonym: "bloodseeker" },
    { name: "Bounty Hunter", imgName: "bounty_hunter.png", className: ClassName.agility, pseudonym: "bounty_hunter" },
    { name: "Brewmaster", imgName: "brewmaster.png", className: ClassName.strength, pseudonym: "brewmaster" },
    { name: "Bristleback", imgName: "bristleback.png", className: ClassName.strength, pseudonym: "bristleback" },
    { name: "Broodmother", imgName: "broodmother.png", className: ClassName.agility, pseudonym: "broodmother" },
    { name: "Centaur Warrunner", imgName: "centaur.png", className: ClassName.strength, pseudonym: "centaur" },
    { name: "Chaos Knight", imgName: "chaos_knight.png", className: ClassName.strength, pseudonym: "chaos_knight" },
    { name: "Chen", imgName: "chen.png", className: ClassName.intelligence, pseudonym: "chen" },
    { name: "Clinkz", imgName: "clinkz.png", className: ClassName.agility, pseudonym: "clinkz" },
    { name: "Clockwerk", imgName: "rattletrap.png", className: ClassName.strength, pseudonym: "rattletrap" },
    { name: "Crystal Maiden", imgName: "crystal_maiden.png", className: ClassName.intelligence, pseudonym: "crystal_maiden" },
    { name: "Dark Seer", imgName: "dark_seer.png", className: ClassName.intelligence, pseudonym: "dark_seer" },
    { name: "Dark Willow", imgName: "dark_willow.png", className: ClassName.intelligence, pseudonym: "dark_willow" },
    { name: "Dawnbreaker", imgName: "dawnbreaker.png", className: ClassName.strength, pseudonym: "dawnbreaker" },
    { name: "Dazzle", imgName: "dazzle.png", className: ClassName.intelligence, pseudonym: "dazzle" },
    { name: "Death Prophet", imgName: "death_prophet.png", className: ClassName.intelligence, pseudonym: "death_prophet" },
    { name: "Disruptor", imgName: "disruptor.png", className: ClassName.intelligence, pseudonym: "disruptor" },
    { name: "Doom", imgName: "doom_bringer.png", className: ClassName.strength, pseudonym: "doom_bringer" },
    { name: "Dragon Knight", imgName: "dragon_knight.png", className: ClassName.strength, pseudonym: "dragon_knight" },
    { name: "Drow Ranger", imgName: "drow_ranger.png", className: ClassName.agility, pseudonym: "drow_ranger" },
    { name: "Earth Spirit", imgName: "earth_spirit.png", className: ClassName.strength, pseudonym: "earth_spirit" },
    { name: "Earthshaker", imgName: "earthshaker.png", className: ClassName.strength, pseudonym: "earthshaker" },
    { name: "Elder Titan", imgName: "elder_titan.png", className: ClassName.strength, pseudonym: "elder_titan" },
    { name: "Ember Spirit", imgName: "ember_spirit.png", className: ClassName.agility, pseudonym: "ember_spirit" },
    { name: "Enchantress", imgName: "enchantress.png", className: ClassName.intelligence, pseudonym: "enchantress" },
    { name: "Enigma", imgName: "enigma.png", className: ClassName.intelligence, pseudonym: "enigma" },
    { name: "Faceless Void", imgName: "faceless_void.png", className: ClassName.agility, pseudonym: "faceless_void" },
    { name: "Grimstroke", imgName: "grimstroke.png", className: ClassName.intelligence, pseudonym: "grimstroke" },
    { name: "Gyrocopter", imgName: "gyrocopter.png", className: ClassName.agility, pseudonym: "gyrocopter" },
    { name: "Hoodwink", imgName: "hoodwink.png", className: ClassName.agility, pseudonym: "hoodwink" },
    { name: "Huskar", imgName: "huskar.png", className: ClassName.strength, pseudonym: "huskar" },
    { name: "Invoker", imgName: "invoker.png", className: ClassName.intelligence, pseudonym: "invoker" },
    { name: "Io", imgName: "wisp.png", className: ClassName.strength, pseudonym: "wisp" },
    { name: "Jakiro", imgName: "jakiro.png", className: ClassName.intelligence, pseudonym: "jakiro" },
    { name: "Juggernaut", imgName: "juggernaut.png", className: ClassName.agility, pseudonym: "juggernaut" },
    { name: "Keeper of the Light", imgName: "keeper_of_the_light.png", className: ClassName.intelligence, pseudonym: "keeper_of_the_light" },
    { name: "Kunkka", imgName: "kunkka.png", className: ClassName.strength, pseudonym: "kunkka" },
    { name: "Legion Commander", imgName: "legion_commander.png", className: ClassName.strength, pseudonym: "legion_commander" },
    { name: "Leshrac", imgName: "leshrac.png", className: ClassName.intelligence, pseudonym: "leshrac" },
    { name: "Lich", imgName: "lich.png", className: ClassName.intelligence, pseudonym: "lich" },
    { name: "Lifestealer", imgName: "life_stealer.png", className: ClassName.strength, pseudonym: "life_stealer" },
    { name: "Lina", imgName: "lina.png", className: ClassName.intelligence, pseudonym: "lina" },
    { name: "Lion", imgName: "lion.png", className: ClassName.intelligence, pseudonym: "lion" },
    { name: "Lone Druid", imgName: "lone_druid.png", className: ClassName.agility, pseudonym: "lone_druid" },
    { name: "Luna", imgName: "luna.png", className: ClassName.agility, pseudonym: "luna" },
    { name: "Lycan", imgName: "lycan.png", className: ClassName.strength, pseudonym: "lycan" },
    { name: "Magnus", imgName: "magnataur.png", className: ClassName.strength, pseudonym: "magnataur" },
    { name: "Mars", imgName: "mars.png", className: ClassName.strength, pseudonym: "mars" },
    { name: "Medusa", imgName: "medusa.png", className: ClassName.agility, pseudonym: "medusa" },
    { name: "Meepo", imgName: "meepo.png", className: ClassName.agility, pseudonym: "meepo" },
    { name: "Mirana", imgName: "mirana.png", className: ClassName.agility, pseudonym: "mirana" },
    { name: "Monkey King", imgName: "monkey_king.png", className: ClassName.agility, pseudonym: "monkey_king" },
    { name: "Morphling", imgName: "morphling.png", className: ClassName.agility, pseudonym: "morphling" },
    { name: "Naga Siren", imgName: "naga_siren.png", className: ClassName.agility, pseudonym: "naga_siren" },
    { name: "Nature's Prophet", imgName: "furion.png", className: ClassName.intelligence, pseudonym: "furion" },
    { name: "Necrophos", imgName: "necrolyte.png", className: ClassName.intelligence, pseudonym: "necrolyte" },
    { name: "Night Stalker", imgName: "night_stalker.png", className: ClassName.strength, pseudonym: "night_stalker" },
    { name: "Nyx Assassin", imgName: "nyx_assassin.png", className: ClassName.agility, pseudonym: "nyx_assassin" },
    { name: "Ogre Magi", imgName: "ogre_magi.png", className: ClassName.intelligence, pseudonym: "ogre_magi" },
    { name: "Omniknight", imgName: "omniknight.png", className: ClassName.strength, pseudonym: "omniknight" },
    { name: "Oracle", imgName: "oracle.png", className: ClassName.intelligence, pseudonym: "oracle" },
    { name: "Outworld Destroyer", imgName: "obsidian_destroyer.png", className: ClassName.intelligence, pseudonym: "obsidian_destroyer" },
    { name: "Pangolier", imgName: "pangolier.png", className: ClassName.agility, pseudonym: "pangolier" },
    { name: "Phantom Assassin", imgName: "phantom_assassin.png", className: ClassName.agility, pseudonym: "phantom_assassin" },
    { name: "Phantom Lancer", imgName: "phantom_lancer.png", className: ClassName.agility, pseudonym: "phantom_lancer" },
    { name: "Phoenix", imgName: "phoenix.png", className: ClassName.strength, pseudonym: "phoenix" },
    { name: "Puck", imgName: "puck.png", className: ClassName.intelligence, pseudonym: "puck" },
    { name: "Pudge", imgName: "pudge.png", className: ClassName.strength, pseudonym: "pudge" },
    { name: "Pugna", imgName: "pugna.png", className: ClassName.intelligence, pseudonym: "pugna" },
    { name: "Queen of Pain", imgName: "queenofpain.png", className: ClassName.intelligence, pseudonym: "queenofpain" },
    { name: "Razor", imgName: "razor.png", className: ClassName.agility, pseudonym: "razor" },
    { name: "Riki", imgName: "riki.png", className: ClassName.agility, pseudonym: "riki" },
    { name: "Rubick", imgName: "rubick.png", className: ClassName.intelligence, pseudonym: "rubick" },
    { name: "Sand King", imgName: "sand_king.png", className: ClassName.strength, pseudonym: "sand_king" },
    { name: "Shadow Demon", imgName: "shadow_demon.png", className: ClassName.intelligence, pseudonym: "shadow_demon" },
    { name: "Shadow Fiend", imgName: "nevermore.png", className: ClassName.agility, pseudonym: "nevermore" },
    { name: "Shadow Shaman", imgName: "shadow_shaman.png", className: ClassName.intelligence, pseudonym: "shadow_shaman" },
    { name: "Silencer", imgName: "silencer.png", className: ClassName.intelligence, pseudonym: "silencer" },
    { name: "Skywrath Mage", imgName: "skywrath_mage.png", className: ClassName.intelligence, pseudonym: "skywrath_mage" },
    { name: "Slardar", imgName: "slardar.png", className: ClassName.strength, pseudonym: "slardar" },
    { name: "Slark", imgName: "slark.png", className: ClassName.agility, pseudonym: "slark" },
    { name: "Snapfire", imgName: "snapfire.png", className: ClassName.strength, pseudonym: "snapfire" },
    { name: "Sniper", imgName: "sniper.png", className: ClassName.agility, pseudonym: "sniper" },
    { name: "Spectre", imgName: "spectre.png", className: ClassName.agility, pseudonym: "spectre" },
    { name: "Spirit Breaker", imgName: "spirit_breaker.png", className: ClassName.strength, pseudonym: "spirit_breaker" },
    { name: "Storm Spirit", imgName: "storm_spirit.png", className: ClassName.intelligence, pseudonym: "storm_spirit" },
    { name: "Sven", imgName: "sven.png", className: ClassName.strength, pseudonym: "sven" },
    { name: "Techies", imgName: "techies.png", className: ClassName.intelligence, pseudonym: "techies" },
    { name: "Templar Assassin", imgName: "templar_assassin.png", className: ClassName.agility, pseudonym: "templar_assassin" },
    { name: "Terrorblade", imgName: "terrorblade.png", className: ClassName.agility, pseudonym: "terrorblade" },
    { name: "Tidehunter", imgName: "tidehunter.png", className: ClassName.strength, pseudonym: "tidehunter" },
    { name: "Timbersaw", imgName: "shredder.png", className: ClassName.strength, pseudonym: "shredder" },
    { name: "Tinker", imgName: "tinker.png", className: ClassName.intelligence, pseudonym: "tinker" },
    { name: "Tiny", imgName: "tiny.png", className: ClassName.strength, pseudonym: "tiny" },
    { name: "Treant Protector", imgName: "treant.png", className: ClassName.strength, pseudonym: "treant" },
    { name: "Troll Warlord", imgName: "troll_warlord.png", className: ClassName.agility, pseudonym: "troll_warlord" },
    { name: "Tusk", imgName: "tusk.png", className: ClassName.strength, pseudonym: "tusk" },
    { name: "Underlord", imgName: "abyssal_underlord.png", className: ClassName.strength, pseudonym: "abyssal_underlord" },
    { name: "Undying", imgName: "undying.png", className: ClassName.strength, pseudonym: "undying" },
    { name: "Ursa", imgName: "ursa.png", className: ClassName.agility, pseudonym: "ursa" },
    { name: "Vengeful Spirit", imgName: "vengefulspirit.png", className: ClassName.agility, pseudonym: "vengefulspirit" },
    { name: "Venomancer", imgName: "venomancer.png", className: ClassName.agility, pseudonym: "venomancer" },
    { name: "Viper", imgName: "viper.png", className: ClassName.agility, pseudonym: "viper" },
    { name: "Visage", imgName: "visage.png", className: ClassName.intelligence, pseudonym: "visage" },
    { name: "Void Spirit", imgName: "void_spirit.png", className: ClassName.intelligence, pseudonym: "void_spirit" },
    { name: "Warlock", imgName: "warlock.png", className: ClassName.intelligence, pseudonym: "warlock" },
    { name: "Weaver", imgName: "weaver.png", className: ClassName.agility, pseudonym: "weaver" },
    { name: "Windranger", imgName: "windrunner.png", className: ClassName.intelligence, pseudonym: "windrunner" },
    { name: "Winter Wyvern", imgName: "winter_wyvern.png", className: ClassName.intelligence, pseudonym: "winter_wyvern" },
    { name: "Witch Doctor", imgName: "witch_doctor.png", className: ClassName.intelligence, pseudonym: "witch_doctor" },
    { name: "Wraith King", imgName: "skeleton_king.png", className: ClassName.strength, pseudonym: "skeleton_king" },
    { name: "Zeus", imgName: "zuus.png", className: ClassName.intelligence, pseudonym: "zuus" }
]