import { ClassName } from "./types/ClassName";
import { Hero } from "./types/Hero";


export const heroes: Array<Hero> = [
    { name: "Abaddon", img: "abaddon.png", className: ClassName.strength, pseudo: "abaddon" },
    { name: "Alchemist", img: "alchemist.png", className: ClassName.strength, pseudo: "alchemist" },
    { name: "Ancient Apparition", img: "ancient_apparition.png", className: ClassName.intelligence, pseudo: "ancient_apparition" },
    { name: "Anti-Mage", img: "antimage.png", className: ClassName.agility, pseudo: "antimage" },
    { name: "Arc Warden", img: "arc_warden.png", className: ClassName.agility, pseudo: "arc_warden" },
    { name: "Axe", img: "axe.png", className: ClassName.strength, pseudo: "axe" },
    { name: "Bane", img: "bane.png", className: ClassName.intelligence, pseudo: "bane" },
    { name: "Batrider", img: "batrider.png", className: ClassName.intelligence, pseudo: "batrider" },
    { name: "Beastmaster", img: "beastmaster.png", className: ClassName.strength, pseudo: "beastmaster" },
    { name: "Bloodseeker", img: "bloodseeker.png", className: ClassName.agility, pseudo: "bloodseeker" },
    { name: "Bounty Hunter", img: "bounty_hunter.png", className: ClassName.agility, pseudo: "bounty_hunter" },
    { name: "Brewmaster", img: "brewmaster.png", className: ClassName.strength, pseudo: "brewmaster" },
    { name: "Bristleback", img: "bristleback.png", className: ClassName.strength, pseudo: "bristleback" },
    { name: "Broodmother", img: "broodmother.png", className: ClassName.agility, pseudo: "broodmother" },
    { name: "Centaur Warrunner", img: "centaur.png", className: ClassName.strength, pseudo: "centaur" },
    { name: "Chaos Knight", img: "chaos_knight.png", className: ClassName.strength, pseudo: "chaos_knight" },
    { name: "Chen", img: "chen.png", className: ClassName.intelligence, pseudo: "chen" },
    { name: "Clinkz", img: "clinkz.png", className: ClassName.agility, pseudo: "clinkz" },
    { name: "Clockwerk", img: "rattletrap.png", className: ClassName.strength, pseudo: "rattletrap" },
    { name: "Crystal Maiden", img: "crystal_maiden.png", className: ClassName.intelligence, pseudo: "crystal_maiden" },
    { name: "Dark Seer", img: "dark_seer.png", className: ClassName.intelligence, pseudo: "dark_seer" },
    { name: "Dark Willow", img: "dark_willow.png", className: ClassName.intelligence, pseudo: "dark_willow" },
    { name: "Dawnbreaker", img: "dawnbreaker.png", className: ClassName.strength, pseudo: "dawnbreaker" },
    { name: "Dazzle", img: "dazzle.png", className: ClassName.intelligence, pseudo: "dazzle" },
    { name: "Death Prophet", img: "death_prophet.png", className: ClassName.intelligence, pseudo: "death_prophet" },
    { name: "Disruptor", img: "disruptor.png", className: ClassName.intelligence, pseudo: "disruptor" },
    { name: "Doom", img: "doom_bringer.png", className: ClassName.strength, pseudo: "doom_bringer" },
    { name: "Dragon Knight", img: "dragon_knight.png", className: ClassName.strength, pseudo: "dragon_knight" },
    { name: "Drow Ranger", img: "drow_ranger.png", className: ClassName.agility, pseudo: "drow_ranger" },
    { name: "Earth Spirit", img: "earth_spirit.png", className: ClassName.strength, pseudo: "earth_spirit" },
    { name: "Earthshaker", img: "earthshaker.png", className: ClassName.strength, pseudo: "earthshaker" },
    { name: "Elder Titan", img: "elder_titan.png", className: ClassName.strength, pseudo: "elder_titan" },
    { name: "Ember Spirit", img: "ember_spirit.png", className: ClassName.agility, pseudo: "ember_spirit" },
    { name: "Enchantress", img: "enchantress.png", className: ClassName.intelligence, pseudo: "enchantress" },
    { name: "Enigma", img: "enigma.png", className: ClassName.intelligence, pseudo: "enigma" },
    { name: "Faceless Void", img: "faceless_void.png", className: ClassName.agility, pseudo: "faceless_void" },
    { name: "Grimstroke", img: "grimstroke.png", className: ClassName.intelligence, pseudo: "grimstroke" },
    { name: "Gyrocopter", img: "gyrocopter.png", className: ClassName.agility, pseudo: "gyrocopter" },
    { name: "Hoodwink", img: "hoodwink.png", className: ClassName.agility, pseudo: "hoodwink" },
    { name: "Huskar", img: "huskar.png", className: ClassName.strength, pseudo: "huskar" },
    { name: "Invoker", img: "invoker.png", className: ClassName.intelligence, pseudo: "invoker" },
    { name: "Io", img: "wisp.png", className: ClassName.strength, pseudo: "wisp" },
    { name: "Jakiro", img: "jakiro.png", className: ClassName.intelligence, pseudo: "jakiro" },
    { name: "Juggernaut", img: "juggernaut.png", className: ClassName.agility, pseudo: "juggernaut" },
    { name: "Keeper of the Light", img: "keeper_of_the_light.png", className: ClassName.intelligence, pseudo: "keeper_of_the_light" },
    { name: "Kunkka", img: "kunkka.png", className: ClassName.strength, pseudo: "kunkka" },
    { name: "Legion Commander", img: "legion_commander.png", className: ClassName.strength, pseudo: "legion_commander" },
    { name: "Leshrac", img: "leshrac.png", className: ClassName.intelligence, pseudo: "leshrac" },
    { name: "Lich", img: "lich.png", className: ClassName.intelligence, pseudo: "lich" },
    { name: "Lifestealer", img: "life_stealer.png", className: ClassName.strength, pseudo: "life_stealer" },
    { name: "Lina", img: "lina.png", className: ClassName.intelligence, pseudo: "lina" },
    { name: "Lion", img: "lion.png", className: ClassName.intelligence, pseudo: "lion" },
    { name: "Lone Druid", img: "lone_druid.png", className: ClassName.agility, pseudo: "lone_druid" },
    { name: "Luna", img: "luna.png", className: ClassName.agility, pseudo: "luna" },
    { name: "Lycan", img: "lycan.png", className: ClassName.strength, pseudo: "lycan" },
    { name: "Magnus", img: "magnataur.png", className: ClassName.strength, pseudo: "magnataur" },
    { name: "Mars", img: "mars.png", className: ClassName.strength, pseudo: "mars" },
    { name: "Medusa", img: "medusa.png", className: ClassName.agility, pseudo: "medusa" },
    { name: "Meepo", img: "meepo.png", className: ClassName.agility, pseudo: "meepo" },
    { name: "Mirana", img: "mirana.png", className: ClassName.agility, pseudo: "mirana" },
    { name: "Monkey King", img: "monkey_king.png", className: ClassName.agility, pseudo: "monkey_king" },
    { name: "Morphling", img: "morphling.png", className: ClassName.agility, pseudo: "morphling" },
    { name: "Naga Siren", img: "naga_siren.png", className: ClassName.agility, pseudo: "naga_siren" },
    { name: "Nature's Prophet", img: "furion.png", className: ClassName.intelligence, pseudo: "furion" },
    { name: "Necrophos", img: "necrolyte.png", className: ClassName.intelligence, pseudo: "necrolyte" },
    { name: "Night Stalker", img: "night_stalker.png", className: ClassName.strength, pseudo: "night_stalker" },
    { name: "Nyx Assassin", img: "nyx_assassin.png", className: ClassName.agility, pseudo: "nyx_assassin" },
    { name: "Ogre Magi", img: "ogre_magi.png", className: ClassName.intelligence, pseudo: "ogre_magi" },
    { name: "Omniknight", img: "omniknight.png", className: ClassName.strength, pseudo: "omniknight" },
    { name: "Oracle", img: "oracle.png", className: ClassName.intelligence, pseudo: "oracle" },
    { name: "Outworld Destroyer", img: "obsidian_destroyer.png", className: ClassName.intelligence, pseudo: "obsidian_destroyer" },
    { name: "Pangolier", img: "pangolier.png", className: ClassName.agility, pseudo: "pangolier" },
    { name: "Phantom Assassin", img: "phantom_assassin.png", className: ClassName.agility, pseudo: "phantom_assassin" },
    { name: "Phantom Lancer", img: "phantom_lancer.png", className: ClassName.agility, pseudo: "phantom_lancer" },
    { name: "Phoenix", img: "phoenix.png", className: ClassName.strength, pseudo: "phoenix" },
    { name: "Puck", img: "puck.png", className: ClassName.intelligence, pseudo: "puck" },
    { name: "Pudge", img: "pudge.png", className: ClassName.strength, pseudo: "pudge" },
    { name: "Pugna", img: "pugna.png", className: ClassName.intelligence, pseudo: "pugna" },
    { name: "Queen of Pain", img: "queenofpain.png", className: ClassName.intelligence, pseudo: "queenofpain" },
    { name: "Razor", img: "razor.png", className: ClassName.agility, pseudo: "razor" },
    { name: "Riki", img: "riki.png", className: ClassName.agility, pseudo: "riki" },
    { name: "Rubick", img: "rubick.png", className: ClassName.intelligence, pseudo: "rubick" },
    { name: "Sand King", img: "sand_king.png", className: ClassName.strength, pseudo: "sand_king" },
    { name: "Shadow Demon", img: "shadow_demon.png", className: ClassName.intelligence, pseudo: "shadow_demon" },
    { name: "Shadow Fiend", img: "nevermore.png", className: ClassName.agility, pseudo: "nevermore" },
    { name: "Shadow Shaman", img: "shadow_shaman.png", className: ClassName.intelligence, pseudo: "shadow_shaman" },
    { name: "Silencer", img: "silencer.png", className: ClassName.intelligence, pseudo: "silencer" },
    { name: "Skywrath Mage", img: "skywrath_mage.png", className: ClassName.intelligence, pseudo: "skywrath_mage" },
    { name: "Slardar", img: "slardar.png", className: ClassName.strength, pseudo: "slardar" },
    { name: "Slark", img: "slark.png", className: ClassName.agility, pseudo: "slark" },
    { name: "Snapfire", img: "snapfire.png", className: ClassName.strength, pseudo: "snapfire" },
    { name: "Sniper", img: "sniper.png", className: ClassName.agility, pseudo: "sniper" },
    { name: "Spectre", img: "spectre.png", className: ClassName.agility, pseudo: "spectre" },
    { name: "Spirit Breaker", img: "spirit_breaker.png", className: ClassName.strength, pseudo: "spirit_breaker" },
    { name: "Storm Spirit", img: "storm_spirit.png", className: ClassName.intelligence, pseudo: "storm_spirit" },
    { name: "Sven", img: "sven.png", className: ClassName.strength, pseudo: "sven" },
    { name: "Techies", img: "techies.png", className: ClassName.intelligence, pseudo: "techies" },
    { name: "Templar Assassin", img: "templar_assassin.png", className: ClassName.agility, pseudo: "templar_assassin" },
    { name: "Terrorblade", img: "terrorblade.png", className: ClassName.agility, pseudo: "terrorblade" },
    { name: "Tidehunter", img: "tidehunter.png", className: ClassName.strength, pseudo: "tidehunter" },
    { name: "Timbersaw", img: "shredder.png", className: ClassName.strength, pseudo: "shredder" },
    { name: "Tinker", img: "tinker.png", className: ClassName.intelligence, pseudo: "tinker" },
    { name: "Tiny", img: "tiny.png", className: ClassName.strength, pseudo: "tiny" },
    { name: "Treant Protector", img: "treant.png", className: ClassName.strength, pseudo: "treant" },
    { name: "Troll Warlord", img: "troll_warlord.png", className: ClassName.agility, pseudo: "troll_warlord" },
    { name: "Tusk", img: "tusk.png", className: ClassName.strength, pseudo: "tusk" },
    { name: "Underlord", img: "abyssal_underlord.png", className: ClassName.strength, pseudo: "abyssal_underlord" },
    { name: "Undying", img: "undying.png", className: ClassName.strength, pseudo: "undying" },
    { name: "Ursa", img: "ursa.png", className: ClassName.agility, pseudo: "ursa" },
    { name: "Vengeful Spirit", img: "vengefulspirit.png", className: ClassName.agility, pseudo: "vengefulspirit" },
    { name: "Venomancer", img: "venomancer.png", className: ClassName.agility, pseudo: "venomancer" },
    { name: "Viper", img: "viper.png", className: ClassName.agility, pseudo: "viper" },
    { name: "Visage", img: "visage.png", className: ClassName.intelligence, pseudo: "visage" },
    { name: "Void Spirit", img: "void_spirit.png", className: ClassName.intelligence, pseudo: "void_spirit" },
    { name: "Warlock", img: "warlock.png", className: ClassName.intelligence, pseudo: "warlock" },
    { name: "Weaver", img: "weaver.png", className: ClassName.agility, pseudo: "weaver" },
    { name: "Windranger", img: "windrunner.png", className: ClassName.intelligence, pseudo: "windrunner" },
    { name: "Winter Wyvern", img: "winter_wyvern.png", className: ClassName.intelligence, pseudo: "winter_wyvern" },
    { name: "Witch Doctor", img: "witch_doctor.png", className: ClassName.intelligence, pseudo: "witch_doctor" },
    { name: "Wraith King", img: "skeleton_king.png", className: ClassName.strength, pseudo: "skeleton_king" },
    { name: "Zeus", img: "zuus.png", className: ClassName.intelligence, pseudo: "zuus" }
]